### ISSUE TITLE
DeleteRange(...) should also do batchFlush(flushBeforeRead) before iterating through DB

### ISSUE THREAD

**Issue by amirtu** [tidwall/raft-leveldb#1]
Hello!

I think there is a missing code block
```
	if err := b.batchFlush(flushBeforeRead); err != nil {
		return err
	}
```
inside the `func (b *LevelDBStore) DeleteRange(min, max uint64) error`
before the
https://github.com/tidwall/raft-leveldb/blob/c33715f6fd63c3b8b5581815151cb7e975815286/leveldb_store.go#L269
line.

**Comment by tidwall** [comment]
Nice find. I just pushed a fix. Thanks for reporting!

**Comment by amirtu** [comment]
Cool, thanks a lot!
